name: pneumonia_classification
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - torchaudio
  - pip
  - pip:
      - kaggle
